### ISSUE TITLE
Tutor page

### ISSUE THREAD

**Issue by kaihaase** [lenneTech/lennelearning#101]
To show who is actively arranging in the academy, we should integrate a team / member / tutor page.

as an extra page with the card-design --> member, specialty, time they are available to ask them questions, etc..

to do:
font-size
responsive on mobile
remove commented code
talk to tutors --> competencies
rename to team-page? 
check if all styles in scss are necessary

**Comment by DKoenig9** [comment]
as an extra page with the card-design --> member, speciality, time they are available to ask them questions

**Comment by RobinZeppenfeld** [comment]
see #150 for further information
